ci:
  autofix_commit_msg: "chore(pre-commit): autofix run"
  autoupdate_commit_msg: "chore(pre-commit): autoupdate hooks"

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npm run lint:check
        language: system
        types: [text]

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v10.0.1
    hooks:
      - id: cspell
        name: check spelling of commit message and staged files
        args:
          - --no-must-find-files
          - --no-progress
          - --no-summary
        stages: [commit-msg, pre-commit]
