services:
  site:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/home/mobimart/site
      - /home/mobimart/site/node_modules
