name: "Check spelling"
on: pull_request

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false # since the next step does not need it
      - uses: streetsidesoftware/cspell-action@v8
        with:
          config: "cspell.json"
          incremental_files_only: true
