name: Weekly Broken Link Check

on:
  schedule:
    - cron: "0 9 * * MON"

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          persist-credentials: false # since the next step does not need it

      - name: Install linkchecker
        run: pip install linkchecker

      - name: Run linkchecker
        id: linkchecker
        run: linkchecker --config=linkcheckerrc --check-extern --verbose https://www.camobilitymarketplace.org
