name: Provider data refresh pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  provider-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: "latest"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - run: bq version

      - run: gsutil version
